import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import useTheme, { ThemeProvider } from "@/contex/ThemeContex";

const source_sans_3 = Source_Sans_3({
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en" className={``}>
        <body className={`${source_sans_3.className} `}>
          <Navbar />
          <main className="mx-auto min-h-svh max-w-screen-xl">{children}</main>
          <footer className="mt-10 bg-gradient-to-tr from-primary to-secondary p-4">
            <div className="mx-auto max-w-screen-xl">
              <p className="text-center text-primary-foreground">Footer</p>
            </div>
          </footer>
        </body>
      </html>
    </ThemeProvider>
  );
}
